import type { LucideIcon } from 'lucide-react';
import {
  Award,
  BookOpen,
  Box,
  Briefcase,
  Brush,
  Calendar,
  Camera,
  Clapperboard,
  Cog,
  Factory,
  Film,
  Flame,
  Gem,
  Hammer,
  HandMetal,
  Heart,
  Highlighter,
  Layers,
  MapPin,
  Mic,
  Music,
  Package,
  Palette,
  Pencil,
  PenTool,
  Plug,
  Scissors,
  Sparkles,
  Star,
  Tag,
  Users,
  Wrench,
  Zap,
} from 'lucide-react';

/** Icon name -> component for event card tag sections. Admins can pick from these. */
export const EVENT_CARD_ICONS: Record<string, LucideIcon> = {
  Sparkles,
  Wrench,
  Hammer,
  Star,
  Users,
  Scissors,
  MapPin,
  Calendar,
  Tag,
  Award,
  Briefcase,
  Factory,
  Gem,
  Heart,
  Palette,
  Camera,
  Film,
  BookOpen,
  Cog,
  Brush,
  Zap,
  PenTool,
  Pencil,
  Highlighter,
  Layers,
  Box,
  Package,
  Mic,
  Music,
  Flame,
  HandMetal,
  Clapperboard,
  Plug,
};

export const DEFAULT_ICONS = {
  producer_icon: 'Sparkles',
  designer_icon: 'Star',
  model_icon: 'Users',
  hair_makeup_icon: 'Scissors',
  city_icon: 'MapPin',
  season_icon: 'Calendar',
  header_tags_icon: 'Tag',
  footer_tags_icon: 'Tag',
} as const;

export function getIcon(name: string | undefined, fallback: keyof typeof DEFAULT_ICONS): LucideIcon {
  const key = name && EVENT_CARD_ICONS[name] ? name : DEFAULT_ICONS[fallback];
  return EVENT_CARD_ICONS[key] || EVENT_CARD_ICONS.Sparkles;
}
